import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const amenities = [
  { name: "Swimming Pool", icon: "🏊", category: "Recreation" },
  { name: "Gym & Fitness Center", icon: "💪", category: "Recreation" },
  { name: "Sauna & Spa", icon: "🧖", category: "Recreation" },
  { name: "Children's Play Area", icon: "🎠", category: "Recreation" },
  { name: "Tennis Court", icon: "🎾", category: "Recreation" },
  { name: "24/7 Security", icon: "🔒", category: "Security" },
  { name: "CCTV Surveillance", icon: "📹", category: "Security" },
  { name: "Concierge Service", icon: "🛎", category: "Services" },
  { name: "Covered Parking", icon: "🚗", category: "Parking" },
  { name: "High-Speed Internet", icon: "📶", category: "Technology" },
  { name: "Smart Home System", icon: "🏠", category: "Technology" },
  { name: "Central A/C", icon: "❄️", category: "Climate" },
  { name: "Built-in Wardrobes", icon: "🚪", category: "Interior" },
  { name: "Maid's Room", icon: "🛏", category: "Interior" },
  { name: "Study Room", icon: "📚", category: "Interior" },
  { name: "Balcony", icon: "🌅", category: "Outdoor" },
  { name: "Private Garden", icon: "🌿", category: "Outdoor" },
  { name: "BBQ Area", icon: "🍖", category: "Outdoor" },
  { name: "Sea View", icon: "🌊", category: "View" },
  { name: "City View", icon: "🏙", category: "View" },
  { name: "Golf View", icon: "⛳", category: "View" },
  { name: "Pets Allowed", icon: "🐾", category: "Policy" },
  { name: "Maintenance Staff", icon: "🔧", category: "Services" },
  { name: "Gymnasium", icon: "🏋️", category: "Recreation" },
];

const properties = [
  {
    title: "Luxury 3-Bedroom Apartment in Dubai Marina",
    description: "Stunning fully-furnished apartment with breathtaking marina views. Features premium finishes, open-plan living, and world-class amenities. Steps from JBR Beach and Dubai Marina Mall.",
    purpose: "RENT" as const, type: "APARTMENT" as const,
    price: 150000, city: "Dubai", community: "Dubai Marina",
    address: "Marina Gate, Sheikh Zayed Road",
    bedrooms: 3, bathrooms: 3, area: 1850, parking: 2, yearBuilt: 2019,
    sellerName: "Mohammed Al Hassan", sellerPhone: "+971501234567", sellerEmail: "mohammed.alhassan@gmail.com",
    featured: true,
    amenities: ["Swimming Pool","Gym & Fitness Center","24/7 Security","Covered Parking","Sea View","Balcony","Central A/C"],
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80"],
  },
  {
    title: "Elegant 5-Bedroom Villa in Palm Jumeirah",
    description: "Exquisite beachfront villa with private pool and direct beach access. Panoramic sea views, gourmet kitchen, and lush tropical gardens.",
    purpose: "BUY" as const, type: "VILLA" as const,
    price: 18500000, city: "Dubai", community: "Palm Jumeirah",
    address: "Frond K, Palm Jumeirah",
    bedrooms: 5, bathrooms: 6, area: 7200, parking: 3, yearBuilt: 2020,
    sellerName: "Sarah Thompson", sellerPhone: "+971509876543", sellerEmail: "sarah.t@outlook.com",
    featured: true,
    amenities: ["Swimming Pool","Private Garden","Sea View","24/7 Security","Smart Home System","Covered Parking","Sauna & Spa","BBQ Area"],
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80","https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80"],
  },
  {
    title: "Modern Studio in Jumeirah Village Circle",
    description: "Affordable, stylish studio with modern finishes. Perfect for first-time buyers or investors. Close to Circle Mall and major highways.",
    purpose: "BUY" as const, type: "STUDIO" as const,
    price: 480000, city: "Dubai", community: "JVC",
    address: "Bloom Towers, JVC",
    bedrooms: 0, bathrooms: 1, area: 450, parking: 1, yearBuilt: 2022,
    sellerName: "Ahmed Khalil", sellerPhone: "+971551112233", sellerEmail: null,
    featured: false,
    amenities: ["Swimming Pool","Gym & Fitness Center","Central A/C","Covered Parking","High-Speed Internet"],
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80","https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80"],
  },
  {
    title: "Spectacular Penthouse in Downtown Dubai",
    description: "Iconic penthouse with 360° views of the Burj Khalifa and Dubai Fountain. Private rooftop terrace and bespoke interiors define this crown jewel.",
    purpose: "BUY" as const, type: "PENTHOUSE" as const,
    price: 32000000, city: "Dubai", community: "Downtown Dubai",
    address: "The Address Downtown, Sheikh Mohammed Bin Rashid Blvd",
    bedrooms: 4, bathrooms: 5, area: 5800, parking: 4, yearBuilt: 2018,
    sellerName: "Priya Sharma", sellerPhone: "+971507654321", sellerEmail: "priya.sharma@gmail.com",
    featured: true,
    amenities: ["Swimming Pool","Gym & Fitness Center","Concierge Service","City View","Smart Home System","Sauna & Spa","24/7 Security"],
    images: ["https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80","https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&q=80"],
  },
  {
    title: "Spacious 2-Bedroom on Abu Dhabi Corniche",
    description: "Prime Corniche location with stunning sea views. Walk to the beach, restaurants, and cultural landmarks. Ideal for families.",
    purpose: "RENT" as const, type: "APARTMENT" as const,
    price: 90000, city: "Abu Dhabi", community: "Corniche",
    address: "Corniche Road West",
    bedrooms: 2, bathrooms: 2, area: 1400, parking: 1, yearBuilt: 2017,
    sellerName: "Fatima Al Zaabi", sellerPhone: "+971528889900", sellerEmail: "fatima.zaabi@hotmail.com",
    featured: false,
    amenities: ["Sea View","Balcony","Central A/C","Covered Parking","24/7 Security","Gymnasium"],
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80","https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80"],
  },
  {
    title: "4-Bedroom Villa in Emirates Hills",
    description: "Prestigious villa overlooking the golf course. Open-plan living areas, private pool, and lush landscaped gardens. An exceptional family home.",
    purpose: "BUY" as const, type: "VILLA" as const,
    price: 14500000, city: "Dubai", community: "Emirates Hills",
    address: "Sector E, Emirates Hills",
    bedrooms: 4, bathrooms: 5, area: 5500, parking: 3, yearBuilt: 2016,
    sellerName: "James Wilson", sellerPhone: "+971504433221", sellerEmail: "j.wilson@yahoo.com",
    featured: true,
    amenities: ["Swimming Pool","Golf View","Private Garden","Maid's Room","Study Room","Smart Home System","BBQ Area"],
    images: ["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80"],
  },
  {
    title: "Contemporary 2-Bedroom in Saadiyat Island",
    description: "Refined apartment near the Louvre Abu Dhabi and pristine beaches. High-end finishes and serene community.",
    purpose: "BUY" as const, type: "APARTMENT" as const,
    price: 1850000, city: "Abu Dhabi", community: "Saadiyat Island",
    address: "Mamsha Al Saadiyat",
    bedrooms: 2, bathrooms: 2, area: 1350, parking: 1, yearBuilt: 2021,
    sellerName: "Layla Mansouri", sellerPhone: "+971506677889", sellerEmail: "layla.m@gmail.com",
    featured: false,
    amenities: ["Sea View","Swimming Pool","Gym & Fitness Center","Balcony","Covered Parking"],
    images: ["https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800&q=80"],
  },
  {
    title: "Family Townhouse in Arabian Ranches",
    description: "Warm 3-bedroom townhouse in sought-after Arabian Ranches. Private garden and friendly neighbourhood.",
    purpose: "RENT" as const, type: "TOWNHOUSE" as const,
    price: 130000, city: "Dubai", community: "Arabian Ranches",
    address: "Al Reem, Arabian Ranches",
    bedrooms: 3, bathrooms: 3, area: 2100, parking: 2, yearBuilt: 2014,
    sellerName: "Omar Farouq", sellerPhone: "+971553344556", sellerEmail: "omar.farouq@gmail.com",
    featured: false,
    amenities: ["Private Garden","Children's Play Area","24/7 Security","Covered Parking","Pets Allowed","BBQ Area"],
    images: ["https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&q=80","https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800&q=80"],
  },
  {
    title: "High-Rise Apartment in Sharjah Waterfront",
    description: "Bright apartment with lagoon views in Sharjah's newest waterfront development. Excellent value and modern facilities.",
    purpose: "BUY" as const, type: "APARTMENT" as const,
    price: 620000, city: "Sharjah", community: "Sharjah Waterfront City",
    address: "Waterfront Tower 3",
    bedrooms: 2, bathrooms: 2, area: 1100, parking: 1, yearBuilt: 2023,
    sellerName: "Rania Khalid", sellerPhone: "+971525566778", sellerEmail: "rania.k@gmail.com",
    featured: false,
    amenities: ["Sea View","Swimming Pool","Gym & Fitness Center","Central A/C","Covered Parking"],
    images: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80"],
  },
  {
    title: "Premium Office Space in DIFC",
    description: "Grade A office in Dubai International Financial Centre. Fully fitted with stunning views and access to world-class amenities.",
    purpose: "RENT" as const, type: "OFFICE" as const,
    price: 280000, city: "Dubai", community: "DIFC",
    address: "Gate District, DIFC",
    bedrooms: 0, bathrooms: 2, area: 2000, parking: 4, yearBuilt: 2015,
    sellerName: "Tariq Al Rashid", sellerPhone: "+971504455667", sellerEmail: "tariq.rashid@business.ae",
    featured: false,
    amenities: ["City View","24/7 Security","CCTV Surveillance","Covered Parking","High-Speed Internet","Central A/C"],
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80"],
  },
  {
    title: "Exclusive Villa in Mohammed Bin Rashid City",
    description: "Ultra-luxury villa with private pool, cinema, and smart home automation. One of Dubai's most coveted addresses.",
    purpose: "BUY" as const, type: "VILLA" as const,
    price: 22000000, city: "Dubai", community: "Mohammed Bin Rashid City",
    address: "District One, MBR City",
    bedrooms: 6, bathrooms: 7, area: 9500, parking: 4, yearBuilt: 2022,
    sellerName: "Khalifa Al Neyadi", sellerPhone: "+971501122334", sellerEmail: "khalifa.neyadi@gmail.com",
    featured: true,
    amenities: ["Swimming Pool","Private Garden","Smart Home System","Sauna & Spa","24/7 Security","City View","Covered Parking"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80","https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800&q=80"],
  },
  {
    title: "Beachfront 1-Bedroom in Al Raha Beach",
    description: "Charming apartment steps from the beach in Abu Dhabi's Al Raha community. Bright interiors and resort-style amenities.",
    purpose: "RENT" as const, type: "APARTMENT" as const,
    price: 65000, city: "Abu Dhabi", community: "Al Raha Beach",
    address: "Al Zeina, Al Raha Beach",
    bedrooms: 1, bathrooms: 1, area: 780, parking: 1, yearBuilt: 2018,
    sellerName: "Hind Al Muhairi", sellerPhone: "+971528899001", sellerEmail: null,
    featured: false,
    amenities: ["Sea View","Swimming Pool","Gym & Fitness Center","Balcony","Central A/C"],
    images: ["https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80"],
  },
  {
    title: "Modern 3-Bedroom in Dubai Hills Estate",
    description: "Elegant apartment with golf course views. Contemporary design, spacious rooms, and access to Dubai Hills Mall.",
    purpose: "BUY" as const, type: "APARTMENT" as const,
    price: 2700000, city: "Dubai", community: "Dubai Hills Estate",
    address: "Golf Place, Dubai Hills",
    bedrooms: 3, bathrooms: 3, area: 1750, parking: 2, yearBuilt: 2021,
    sellerName: "Nour Al Amri", sellerPhone: "+971509988776", sellerEmail: "nour.alamri@gmail.com",
    featured: false,
    amenities: ["Golf View","Swimming Pool","Gym & Fitness Center","Children's Play Area","Covered Parking","Central A/C"],
    images: ["https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800&q=80"],
  },
  {
    title: "Affordable 2-Bedroom in Ajman Corniche",
    description: "Value-for-money apartment on the Ajman Corniche with sea views. Ideal for families or investors.",
    purpose: "BUY" as const, type: "APARTMENT" as const,
    price: 380000, city: "Ajman", community: "Ajman Corniche",
    address: "Ajman Corniche Road",
    bedrooms: 2, bathrooms: 2, area: 1100, parking: 1, yearBuilt: 2016,
    sellerName: "Youssef Bitar", sellerPhone: "+971561122334", sellerEmail: "youssef.bitar@yahoo.com",
    featured: false,
    amenities: ["Sea View","Balcony","Covered Parking","Central A/C"],
    images: ["https://images.unsplash.com/photo-1565182999561-18d7dc61c393?w=800&q=80"],
  },
  {
    title: "Furnished Studio in Business Bay",
    description: "Fully furnished studio with canal views in the heart of Business Bay. Walk to Dubai Mall, perfect for professionals.",
    purpose: "RENT" as const, type: "STUDIO" as const,
    price: 55000, city: "Dubai", community: "Business Bay",
    address: "The Opus, Business Bay",
    bedrooms: 0, bathrooms: 1, area: 420, parking: 1, yearBuilt: 2020,
    sellerName: "Zara Ahmed", sellerPhone: "+971507788990", sellerEmail: "zara.ahmed@gmail.com",
    featured: false,
    amenities: ["City View","Swimming Pool","Gym & Fitness Center","High-Speed Internet","Concierge Service"],
    images: ["https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80"],
  },
  {
    title: "4-Bedroom Townhouse in Jumeirah",
    description: "Generously sized townhouse with huge garden and spacious bedrooms. Family-friendly community close to the beach.",
    purpose: "RENT" as const, type: "TOWNHOUSE" as const,
    price: 200000, city: "Dubai", community: "Jumeirah",
    address: "Jumeirah 2, Al Safa",
    bedrooms: 4, bathrooms: 4, area: 3200, parking: 2, yearBuilt: 2012,
    sellerName: "Khalid Al Serkal", sellerPhone: "+971503344557", sellerEmail: null,
    featured: false,
    amenities: ["Private Garden","Maid's Room","Study Room","Covered Parking","Pets Allowed","BBQ Area"],
    images: ["https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&q=80"],
  },
  {
    title: "Duplex Penthouse in JBR with Marina Views",
    description: "Rare duplex penthouse with wraparound terrace and stunning sea and marina views at JBR Walk.",
    purpose: "BUY" as const, type: "PENTHOUSE" as const,
    price: 9800000, city: "Dubai", community: "JBR",
    address: "Sadaf Building, JBR Walk",
    bedrooms: 4, bathrooms: 5, area: 4200, parking: 3, yearBuilt: 2017,
    sellerName: "Elena Petrova", sellerPhone: "+971505566778", sellerEmail: "elena.petrova@gmail.com",
    featured: true,
    amenities: ["Sea View","Swimming Pool","Gym & Fitness Center","24/7 Security","Balcony","Sauna & Spa"],
    images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80"],
  },
  {
    title: "Modern 2-Bedroom in Reem Island",
    description: "Stylish apartment on Abu Dhabi's Reem Island with partial sea views. Walking distance to Shams Abu Dhabi mall.",
    purpose: "BUY" as const, type: "APARTMENT" as const,
    price: 1100000, city: "Abu Dhabi", community: "Reem Island",
    address: "Sky Tower, Reem Island",
    bedrooms: 2, bathrooms: 2, area: 1250, parking: 1, yearBuilt: 2019,
    sellerName: "Hassan Al Blooshi", sellerPhone: "+971522334455", sellerEmail: "hassan.blooshi@gmail.com",
    featured: false,
    amenities: ["Sea View","Swimming Pool","Gym & Fitness Center","Balcony","Central A/C"],
    images: ["https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80"],
  },
  {
    title: "1-Bedroom Apartment on Yas Island",
    description: "Well-priced apartment on Abu Dhabi's entertainment island. Close to Yas Mall, Ferrari World and the Formula 1 circuit.",
    purpose: "BUY" as const, type: "APARTMENT" as const,
    price: 750000, city: "Abu Dhabi", community: "Yas Island",
    address: "Yas Acres, Yas Island",
    bedrooms: 1, bathrooms: 1, area: 850, parking: 1, yearBuilt: 2020,
    sellerName: "Mona Al Shamsi", sellerPhone: "+971509911223", sellerEmail: "mona.shamsi@gmail.com",
    featured: false,
    amenities: ["Swimming Pool","Gym & Fitness Center","Children's Play Area","Covered Parking","Central A/C"],
    images: ["https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80"],
  },
  {
    title: "Investment Land in Sharjah Industrial Area",
    description: "Prime industrial land plot with excellent highway access. Ideal for warehousing, light manufacturing or logistics.",
    purpose: "BUY" as const, type: "LAND" as const,
    price: 2200000, city: "Sharjah", community: "Sharjah Industrial Area",
    address: "Industrial Area 4, Sharjah",
    bedrooms: 0, bathrooms: 0, area: 15000, areaUnit: "sqm", parking: 0,
    sellerName: "Adel Al Qassimi", sellerPhone: "+971556677889", sellerEmail: "adel.qassimi@outlook.com",
    featured: false, amenities: [],
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80"],
  },
];

function slugify(str: string) {
  return str.toLowerCase().replace(/[^a-z0-9\s-]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-").trim();
}

async function main() {
  console.log("🌱 Seeding database...");
  await prisma.propertyAmenity.deleteMany();
  await prisma.propertyImage.deleteMany();
  await prisma.property.deleteMany();
  await prisma.amenity.deleteMany();
  console.log("✅ Cleaned existing data");

  const amenityRecords = await Promise.all(amenities.map((a) => prisma.amenity.create({ data: a })));
  const amenityMap = Object.fromEntries(amenityRecords.map((a) => [a.name, a.id]));
  console.log(`✅ Created ${amenityRecords.length} amenities`);

  for (const p of properties) {
    const slug = slugify(p.title) + "-" + Math.random().toString(36).slice(2, 6);
    const { images, amenities: propAmenities, areaUnit, yearBuilt, ...rest } = p;
    await prisma.property.create({
      data: {
        ...rest,
        slug,
        areaUnit: areaUnit ?? "sqft",
        yearBuilt: yearBuilt ?? null,
        images: { create: images.map((url, i) => ({ url, isPrimary: i === 0, order: i })) },
        amenities: { create: propAmenities.filter((n) => amenityMap[n]).map((n) => ({ amenityId: amenityMap[n] })) },
      },
    });
    console.log(`  ✅ ${p.title}`);
  }
  console.log(`\n✅ Created ${properties.length} properties\n🎉 Seeding complete!`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
